Atacseq:
    document_ids: []

Batch:
    crosslinking_method: formaldehyde

BatchItem:
    concentration_unit: 10 #ng/µl

CrisprModification:
    category: insertion
    purpose: tagging
    document_ids: [38, 39]

ChipseqExperiment:
    document_ids: [10]

DonorConstruct:
    insertion_region: "C-terminal"

Gel:
    percentage_for_IP: 4-15
    percentage_for_PCR: 1

GelLane:
    sample_volume: 7

Immunoblot:
    primary_antibody_id: 9
    primary_antibody_dilution: 1:2000
    secondary_antibody_ids: [11]
    secondary_antibody_dilution: 1:10000

Library:
    concentration_unit_id: 10 # ng/µl
    library_fragmentation_method_id: 14 # sonication (Bioruptor Pico)
    nucleic_acid_term_id: 1 # DNA
    sequencing_library_prep_kit_id: 6 # Custom ChIP-seq library kit (Snyder lab)
    size_range: 250-450

Pcr:
    genomic_dna_concentration_units_id: # 10 ng/µl

SequencingRequest:
    concentration_instrument: Qubit
    sequencing_center: 1 #Stanford Genome Sequencing Service Center
    concentration_unit: 10 #ng/µl
    sequencing_platform: 3 #illumina hiseq 4000
