
ChipBatch:
    crosslinking_method: formaldehyde

ChipBatchItem:
    concentration_unit: 10 #ng/µl

Gel:
    percentage: 4-15

GelLane:
    sample_volume: 7

Immunoblot:
    primary_antibody_id: 9
    primary_antibody_dilution: 1:2000
    secondary_antibody_ids: [11]
    secondary_antibody_dilution: 1:10000

SequencingRequest:
    concentration_instrument: Qubit
    sequencing_center: 1 #Stanford Genome Sequencing Service Center
    concentration_unit: 10 #ng/µl
    sequencing_platform: 3 #illumina hiseq 4000
